export default {
  FETCH_MEETUP: 'meetup/FETCH_MEETUP',
  FETCH_MEETUP_SUCCESS: 'meetup/FETCH_MEETUP_SUCCESS',
  CREATE_UPDATE_MEETUP: 'meetup/CREATE_UPDATE_MEETUP',
  // CREATE_MEETUP_SUCCESS: 'meetup/CREATE_MEETUP_SUCCESS',
  ATTEND_MEETUP: 'meetup/ATTEND_MEETUP',
  // ATTEND_MEETUP_SUCCESS: 'meetup/ATTEND_MEETUP_SUCCESS',
  CANCEL_MEETUP: 'meetup/CANCEL_MEETUP',
  // CANCEL_MEETUP_SUCCESS: 'meetup/CANCEL_MEETUP_SUCCESS',
  SUCCESS: 'meetup/SUCCESS',
  FAILURE: 'meetup/FAILURE',
}
