export default {
  CREATE_MEETUP: 'meetup/CREATE_MEETUP',
  CREATE_MEETUP_SUCCESS: 'meetup/CREATE_MEETUP_SUCCESS',
  ATTEND_MEETUP: 'meetup/ATTEND_MEETUP',
  ATTEND_MEETUP_SUCCESS: 'meetup/ATTEND_MEETUP_SUCCESS',
  FAILURE: 'meetup/FAILURE',
}
